EXE=lisp.pdf
SRC=lisp.tex
BIB=lisp.aux

$(EXE):$(SRC)      ;    xelatex $(SRC)

.PHONY.:look
look:              ;    evince lisp.pdf

.PHONY.:clean
clean:             ;    $(RM) lisp.aux lisp.log lisp.pdf lisp.dvi lisp.bbl lisp.blg lisp.toc lisp.out lisp.nav lisp.snm lisp.thm lisp.lot lisp.lof
