EXE=ribll.pdf
SRC=ribll.tex
BIB=ribll.aux

$(EXE):$(SRC)      ;    xelatex $(SRC)

.PHONY.:look
look:              ;    evince ribll.pdf

.PHONY.:clean
clean:             ;    $(RM) ribll.aux ribll.log ribll.pdf ribll.dvi ribll.bbl ribll.blg ribll.toc ribll.out ribll.nav ribll.snm ribll.thm
